### ISSUE TITLE
Test Branch

### ISSUE THREAD

**Issue by bualdoot** [noxsicarius/Epoch-Admin-Tools#257] opened 2015-02-16 10:15 UTC
I updated to the newest version of TestBranch, but I'm thinking I may have jumped the gun. Wanted to see the new GUI, but either you forgot to add "admintools\tools\buildingsDialog.sqf", or you just haven't created it yet. Error pops up when I try to select it. Also, trying to place items no longer works.

RPT log:

Warning Message: Script admintools\tools\buildingsDialog.sqf not found
Error in expression <his select 0;
adminRebuildItem = _item;
if(_this select 1) then {isBuilding = tr>
  Error position: <if(_this select 1) then {isBuilding = tr>
  Error if: Type String, expected Bool
File mpmissions\__CUR_MP.Napf\admintools\tools\AdminBuild\adminBuild.sqf, line 41
Error in expression <his select 0;
adminRebuildItem = _item;
if(_this select 1) then {isBuilding = tr>
  Error position: <if(_this select 1) then {isBuilding = tr>
  Error if: Type String, expected Bool
File mpmissions\__CUR_MP.Napf\admintools\tools\AdminBuild\adminBuild.sqf, line 41

Tried using admin build to place a sandbag wall, as well as cinderwall.

**Comment by noxsicarius** [comment] 2015-02-16 17:08
I have all of this stuff fixed on my test branch, there is still one issue I was working on fixing before committing though

**Comment by noxsicarius** [comment] 2015-02-16 20:48
Uploaded my current test branch changes. The one thing not working in the building right now is the permanent arma buildings. I am not sure why yet as it worked during testing with my old gui.

**Comment by bualdoot** [comment] 2015-02-17 02:05
Sweet. I'll update to the newer test build and test it out also. Looking
forward to it!

**Comment by bualdoot** [comment] 2015-02-17 03:30
Deleted my admintools folder after Diffmerg my config file (for admins) into the testbranch version I just downloaded, and then moved the new folder to my root mission directory, so I know everything is current. But, I still can't place any objects I've tried so far. The GUI looks fantastic, I'll try placing stuff from it once I finish this post. But, I tried placing cinderwall and once I select the object, menu goes away and nothing happens. I did notice this error in client RPT after trying to place it. So, maybe this is the culprit.

adminRebuildItem = _item;
if(_this select 1) then {isBuilding = tr>
  Error position: <if(_this select 1) then {isBuilding = tr>
  Error if: Type String, expected Bool
File mpmissions\__CUR_MP.Napf\admintools\tools\AdminBuild\adminBuild.sqf, line 41

**Comment by bualdoot** [comment] 2015-02-17 03:37
Another error in client RPT

Error in expression < format["%1 - %2 (%3)", _x select 0, _x select 1, _x select 2]];
lbSetPicture [A>
  Error position: <select 1, _x select 2]];
lbSetPicture [A>
  Error Zero divisor
File mpmissions\__CUR_MP.Napf\admintools\tools\buildingsDialog.sqf, line 64

**Comment by noxsicarius** [comment] 2015-02-17 03:56
Weird, I fixed that boolean error a good while ago

**Comment by noxsicarius** [comment] 2015-02-17 03:58
OH, I canceled my commit of adminbuild.sqf because you made a change to the spelling. I thought the only change I made was that and I forgot about the rest. I figured it would be nicer if you had credit for it instead.

**Comment by bualdoot** [comment] 2015-02-17 04:02
Ya, just started getting the boolean error with the two versions of testbranch from this weekend/today. I guess I could have compared the file too the master and seen what was in there. My problem/luck would be that both files would be the same, and then I wouldnt know what too do, other than google some about boolean vs string, since I can't remember the difference in format.

And thanks for the credit for false :) One of these days I'll fix a problem before the creator finds it also, hehe.

**Comment by noxsicarius** [comment] 2015-02-17 04:08
Well it should work fine now. I changed the fix into the admintoolsmain because it works better there. That zero divisor issue shouldn't be a problem. I am still looking into it, but I don't see the issue right now.

**Comment by noxsicarius** [comment] 2015-02-17 04:11
Epoch items will build fine (permanently), but the arma buildings are still only temp from what I know. If you try it perm it will let you position it, but pressing space makes it disappear. I find it odd because I had it working perfectly in my old gui and I didn't change that part.

Actually I have an idea that it may be caused by a local variable being used instead of global. Will take some testing.

**Comment by bualdoot** [comment] 2015-02-17 04:14
Ahh. Well, I'll check it out then. Ya, the zero divisor I'm not too worried about. I have one other mod that gives the same thing, but seems fine...Zupa's zombie walkers I think it is. Boolean on the other hand is the only error i can think was making the item not appear for placement. So, I'll give the fix a go!

**Closed** 2015-03-09 23:07 UTC
