### ISSUE TITLE
God Mod issue

### ISSUE THREAD

**Issue by AssoMania** [noxsicarius/Epoch-Admin-Tools#291] opened 2016-02-02 09:23 UTC
Hey there,

I installed the code, it work perfectly I just have some troubles with the god mod. Once active via F4 the Z can still kill me, bots also. Basically anyone.
If I turn it off and on again I get back my life but still no god mod

**Comment by noxsicarius** [comment] 2016-02-02 16:56
What version?
What are the exact steps to replicate?
How often does it happen? (from the moment of login it never works, it stops after a few minutes, ...)

**Comment by AssoMania** [comment] 2016-02-02 20:39
I use the last one 1.10
I'm in the middle of the Z, use the scroll to activate the Admin menu.
Automatically I should have the GodMod on and it is not working. As I said I tried to turn it off and on again I get back full life but after I still take damage (from Z or AI)
It happens straight away on the server start. Basically anytime

**Comment by noxsicarius** [comment] 2016-02-03 05:26
Are you using infistar safe zone?

**Comment by AssoMania** [comment] 2016-02-03 08:49
No nothing from infistar but I saw this issue in game 
I send the screen
![godmod](https://cloud.githubusercontent.com/assets/17022609/12777180/64b6e9fc-ca5b-11e5-8466-52bba11dabd2.jpg)

**Comment by Evocation** [comment] 2016-02-03 09:24
ohh.. yes i saw this error once too, but fixed it myself and forgot to report it ^^

u should check for it in your admin tools varribles.sqf and define it, if its not declared there :)

**Comment by AssoMania** [comment] 2016-02-03 10:23
The lines are in the variables.sqf for both godmod and vehicles
At the beginning I can also see that it is looking into the SuperAdmin and Admin List
followed by the Admin and the Modlist so thats also ok
I don't know where its coming from
Also the flying mod : my char is going in the air but i can't move, is that normal ?
The stealth mod is working, like the infinite ammo for exemple

Any other ideas ?

**Comment by Evocation** [comment] 2016-02-03 12:11
u cant move? do u press q for flying? dont touch spacebar.. thats for hovering and wont let u move around...

another idea is to delete all expressions with the broadcasttooluse variable... thats what i did to fix it, because i dont need this option ^^

**Comment by AssoMania** [comment] 2016-02-03 12:33
Sorry for the flying, my bad its working
I deleted the : && broadcastToolUse)  in the godmodeplayer.sqf, still a error
I tried to remove this entire line :

	// Tool use broadcaster
	if(!((getPlayerUID _player) in SuperAdminList) && broadcastToolUse) then {
		useBroadcaster = format["%1 -- has DISABLED god mode",name _player];
		[] spawn {publicVariableServer "useBroadcaster";};
	};

no error message but still not working

**Comment by AssoMania** [comment] 2016-02-03 12:42
And same when I turn it off and on again I get back all my life and I'm not bleeding anymore or so but if I get hit again I'm loosing HP

**Comment by noxsicarius** [comment] 2016-02-03 12:58
The tool use thing shouldn't cause issues with the mod. It was left over code from something that was removed. It's been fixed in the test branch for a few months now. To stop the error you could just add bradcastToolUse = false; anywhere in the config file.

**Comment by noxsicarius** [comment] 2016-02-03 13:19
The only thing that can cause this is something that modifies damage like a safe zone

**Comment by AssoMania** [comment] 2016-02-03 13:58
I'm in the middle of nowhere when it happens against zombies. No safe zone or something
I will try the bradcastToolUse = false; and I let you know

**Comment by AssoMania** [comment] 2016-02-03 16:33
bradcastToolUse = false;
Makes the Admin menu dissapear completly :/

**Comment by noxsicarius** [comment] 2016-02-03 17:40
What scripts do you have installed? I'm pretty sure it is one of these unless an error was introduced by you somehow.

**Comment by AssoMania** [comment] 2016-02-04 14:26
A lot of things .. I'm running a OverPochIns server
DZGM, CKC, plotmanagement, service point, zupa, tow and lift and more

**Comment by noxsicarius** [comment] 2016-02-04 14:33
Anything that modifies damage?

**Comment by AssoMania** [comment] 2016-02-16 06:22
Safe zone, but appart from that I don't think so, you want to see the god script ?

**Comment by noxsicarius** [comment] 2016-02-16 15:02
It seems like something is interfering with the script. You could try installing the test branch instead. This branch is stable and almost entirely working. It also comes with it's own safe zone system so we can be sure that isn't the issue (lots of options, works on every map, has exclusion for god mode so it doesn't turn it off). I know the normal branch works fine without any problems on a clean server, but there may be some kind of corruption or install error. The test branch has more features and faster code anyway. I will probably be releasing it as a new version after a few more additions. The edits have gotten too big to keep waiting for 2.0 to be done.

**Comment by slayterson** [comment] 2016-02-16 17:03
Did you double check the install steps? Making sure to bypass the built in antihack for admins. And set be filters.

**Comment by noxsicarius** [comment] 2016-02-16 17:16
The antihack only really affects teleport. There are very few possibilities that could cause this issue with god mode: script error, damage handling in another script and variable collision with another script. The most common is caused by using infistar safe zones, which is no longer necessary as I have bundled a new custom one with the test branch (and also offer it separately which works with infistar too). He never stated which safe zone was in use, but did say it isn't infistar. I really think it's one of the installed mods, but as I can't get a complete list I can't asses if that is the issue. I know for sure the test branch is working fine as I have been fixing all errors I can find in it recently. If this is installed and doesn't work we know it is something else interfering with it. An rpt log would help as well. Preferably both client and server.

**Comment by AssoMania** [comment] 2016-02-16 18:30
Thanks for all your reply guys 
I will wait for the new branch to come out thats ok

**Closed** 2016-03-05 19:10 UTC
